//! Golden-file regression tests for asperitas-cli DSP processors.
//!
//! Two kinds of input feed the same comparison: deterministic signals generated by
//! `synth`, and the recorded instrument clips in `audio/instruments/` (TASK-008.02).
//! Output is frozen as a listenable WAV under `audio/goldens/`.
//!
//! Set `UPDATE_GOLDENS=1` to regenerate goldens. This is deliberately explicit: a
//! golden diff means "listen to this before accepting it", not "run the update
//! command". That distinction is the whole value of the mechanism.

use asperitas_cli::synth;
use asperitas_cli::wav_io;
use asperitas_dsp::filter::OnePoleLowPass;
use asperitas_dsp::gain::Gain;
use asperitas_dsp::processor::{Frame, Processor};

const GOLDEN_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../audio/goldens");
const CORPUS_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../audio/instruments");
const SAMPLE_RATE: u32 = 48000;
const DURATION: f32 = 1.0;

/// Tolerance for per-sample comparison (absolute delta).
/// Accounts for double 16-bit quantization round-trip (write + read).
const TOLERANCE: f32 = 1e-4;

/// Where a golden case's input comes from.
enum Input {
    /// A signal generated by `synth` at [`SAMPLE_RATE`] for [`DURATION`].
    Synthetic(&'static str),
    /// A recorded instrument clip, by file stem in `audio/instruments/`.
    Clip(&'static str),
}

impl Input {
    /// The input frames, plus the sample rate the processor should be configured for.
    ///
    /// Clips report their own rate from the file header rather than assuming 48 kHz,
    /// so this exercises the same `set_sample_rate` path the CLI uses for arbitrary
    /// user files.
    fn frames(&self) -> (Vec<Frame>, u32) {
        match self {
            Input::Synthetic(kind) => {
                let mono = match *kind {
                    "impulse" => synth::generate_impulse(SAMPLE_RATE, DURATION),
                    "sweep" => synth::generate_sweep(SAMPLE_RATE, DURATION),
                    "pluck" => synth::generate_pluck(SAMPLE_RATE, DURATION, 440.0),
                    other => panic!("unknown synthetic signal: {other}"),
                };
                (synth::to_stereo(&mono), SAMPLE_RATE)
            }
            // The corpus is mono; read_wav widens it into stereo frames.
            Input::Clip(stem) => {
                let path = format!("{CORPUS_DIR}/{stem}.wav");
                let (spec, frames) = wav_io::read_wav(&path)
                    .unwrap_or_else(|e| panic!("cannot read corpus clip '{path}': {e}"));
                (frames, spec.sample_rate)
            }
        }
    }

    fn slug(&self) -> &'static str {
        match self {
            Input::Synthetic(s) | Input::Clip(s) => s,
        }
    }
}

/// Run `P` at default parameters over `input` and compare against the stored golden,
/// or overwrite that golden when `UPDATE_GOLDENS` is set.
fn run_golden<P>(processor: &str, input: &Input)
where
    P: Processor + Default,
{
    let (frames, sample_rate) = input.frames();

    let mut output = vec![Frame::default(); frames.len()];
    let mut proc = P::default();
    proc.set_sample_rate(sample_rate as f32);
    proc.set_params(&P::Params::default());
    proc.process_block(&frames, &mut output);

    let slug = input.slug();
    let path = format!("{GOLDEN_DIR}/{processor}_default_{slug}.wav");
    let label = format!("{processor}+{slug}");

    if std::env::var("UPDATE_GOLDENS").is_ok() {
        wav_io::write_wav(&path, sample_rate, &output)
            .unwrap_or_else(|e| panic!("failed to write golden {label}: {e}"));
        return;
    }

    compare_golden(&path, &output, &label);
}

/// Declare one `#[test]` per (processor, input) pair.
///
/// One test per case rather than a loop over the corpus, so a failure names the exact
/// clip that drifted and can be re-run on its own while you listen to it.
macro_rules! golden_cases {
    ($($name:ident: $proc:ty = $label:literal over $input:expr;)*) => {
        $(
            #[test]
            fn $name() {
                run_golden::<$proc>($label, &$input);
            }
        )*
    };
}

// -- Synthetic signals --

golden_cases! {
    golden_gain_impulse: Gain = "gain" over Input::Synthetic("impulse");
    golden_gain_sweep: Gain = "gain" over Input::Synthetic("sweep");
    golden_gain_pluck: Gain = "gain" over Input::Synthetic("pluck");
    golden_filter_impulse: OnePoleLowPass = "filter" over Input::Synthetic("impulse");
    golden_filter_sweep: OnePoleLowPass = "filter" over Input::Synthetic("sweep");
    golden_filter_pluck: OnePoleLowPass = "filter" over Input::Synthetic("pluck");
}

// -- Recorded instrument corpus (TASK-008.02) --
//
// Both processors run at their defaults over all eight clips. Note that `Gain`'s
// default is 0 dB, so these goldens are near-copies of the input; they guard the
// read/widen/process/write chain over real material rather than the gain maths,
// which the synthetic cases cover.

golden_cases! {
    golden_gain_mandolin_single_note_soft: Gain
        = "gain" over Input::Clip("mandolin_single_note_soft");
    golden_gain_mandolin_single_note_hard: Gain
        = "gain" over Input::Clip("mandolin_single_note_hard");
    golden_gain_mandolin_fast_run: Gain
        = "gain" over Input::Clip("mandolin_fast_run");
    golden_gain_mandolin_chord: Gain
        = "gain" over Input::Clip("mandolin_chord");
    golden_gain_octave_mandolin_single_note_soft: Gain
        = "gain" over Input::Clip("octave_mandolin_single_note_soft");
    golden_gain_octave_mandolin_single_note_hard: Gain
        = "gain" over Input::Clip("octave_mandolin_single_note_hard");
    golden_gain_octave_mandolin_fast_run: Gain
        = "gain" over Input::Clip("octave_mandolin_fast_run");
    golden_gain_octave_mandolin_chord: Gain
        = "gain" over Input::Clip("octave_mandolin_chord");

    golden_filter_mandolin_single_note_soft: OnePoleLowPass
        = "filter" over Input::Clip("mandolin_single_note_soft");
    golden_filter_mandolin_single_note_hard: OnePoleLowPass
        = "filter" over Input::Clip("mandolin_single_note_hard");
    golden_filter_mandolin_fast_run: OnePoleLowPass
        = "filter" over Input::Clip("mandolin_fast_run");
    golden_filter_mandolin_chord: OnePoleLowPass
        = "filter" over Input::Clip("mandolin_chord");
    golden_filter_octave_mandolin_single_note_soft: OnePoleLowPass
        = "filter" over Input::Clip("octave_mandolin_single_note_soft");
    golden_filter_octave_mandolin_single_note_hard: OnePoleLowPass
        = "filter" over Input::Clip("octave_mandolin_single_note_hard");
    golden_filter_octave_mandolin_fast_run: OnePoleLowPass
        = "filter" over Input::Clip("octave_mandolin_fast_run");
    golden_filter_octave_mandolin_chord: OnePoleLowPass
        = "filter" over Input::Clip("octave_mandolin_chord");
}

// -- Golden comparison helper --

fn compare_golden(path: &str, expected: &[Frame], label: &str) {
    if !std::path::Path::new(path).exists() {
        panic!(
            "golden file not found: {path}\n\
             Run `UPDATE_GOLDENS=1 cargo test -p asperitas-cli` to generate it."
        );
    }

    let (_, actual) = wav_io::read_wav(path)
        .unwrap_or_else(|e| panic!("cannot read golden {label} at {path}: {e}"));

    assert_eq!(
        actual.len(),
        expected.len(),
        "golden {label}: length mismatch (expected {} samples, got {})",
        expected.len(),
        actual.len()
    );

    let mut max_delta = 0.0f32;
    for (i, (exp, act)) in expected.iter().zip(actual.iter()).enumerate() {
        for ch in 0..2 {
            let delta = (exp[ch] - act[ch]).abs();
            if delta > max_delta {
                max_delta = delta;
            }
            let exp_val = exp[ch];
            let act_val = act[ch];
            assert!(
                delta < TOLERANCE,
                "golden {label}: sample [{i}] channel {ch} differs by {delta:.8} \
                 (expected {exp_val:.8}, got {act_val:.8}) (tolerance {TOLERANCE})"
            );
        }
    }

    if max_delta > 0.0 {
        eprintln!(
            "golden {label}: max sample delta = {max_delta:.2e} (within tolerance {TOLERANCE})"
        );
    }
}
